// User
const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
const PURCHASE_VOUCHER = 'PURCHASE_VOUCHER';
const LOG_OUT_USER = 'LOG_OUT_USER';

// Teams
const FETCH_TEAMS = 'FETCH_TEAMS';

// Games
const FETCH_GAMES_BY_TEAM_ID = 'FETCH_GAMES_BY_TEAM_ID';
const FETCH_GAME_STATISTIC_BY_ID = 'FETCH_GAME_STATISTIC_BY_ID';
const SELECT_GAME_STATUS_ID = 'SELECT_GAME_STATUS_ID';
const SELECT_GAME_ID = 'SELECT_GAME_ID';
const SELECT_GAME_STATS_VIEW = 'SELECT_GAME_STATS_VIEW';
const SELECT_GAME_STATS_INDEX = 'SELECT_GAME_STATS_INDEX';

// Athletes
const FETCH_ATHLETE_PROFILE_BY_ID = 'FETCH_ATHLETE_PROFILE_BY_ID';

export {
  AUTHENTICATE_USER,
  LOG_OUT_USER,
  PURCHASE_VOUCHER,
  FETCH_TEAMS,
  FETCH_GAMES_BY_TEAM_ID,
  FETCH_GAME_STATISTIC_BY_ID,
  SELECT_GAME_STATUS_ID,
  SELECT_GAME_ID,
  SELECT_GAME_STATS_VIEW,
  SELECT_GAME_STATS_INDEX,
  FETCH_ATHLETE_PROFILE_BY_ID,
};
