// App
const TOGGLE_NAVIGATION_MENU_OPEN_STATE = 'TOGGLE_NAVIGATION_MENU_OPEN_STATE';

// Teams
const FETCH_TEAMS = 'FETCH_TEAMS';

// Games
const FETCH_GAMES_BY_TEAM_ID = 'FETCH_GAMES_BY_TEAM_ID';
const FILTER_GAMES_BY_STATUS_ID = 'FILTER_GAMES_BY_STATUS_ID';
const SEGMENT_GAMES_BY_STATUS = 'SEGMENT_GAMES_BY_STATUS';

export {
  TOGGLE_NAVIGATION_MENU_OPEN_STATE,
  FETCH_TEAMS,
  FETCH_GAMES_BY_TEAM_ID,
  FILTER_GAMES_BY_STATUS_ID,
  SEGMENT_GAMES_BY_STATUS,
};
