// Teams
const FETCH_TEAMS = 'FETCH_TEAMS';

// Games
const FETCH_GAMES_BY_TEAM_ID = 'FETCH_GAMES_BY_TEAM_ID';
const FETCH_GAME_STATISTIC_BY_ID = 'FETCH_GAME_STATISTIC_BY_ID';
const FILTER_GAMES_BY_STATUS_ID = 'FILTER_GAMES_BY_STATUS_ID';

// Athletes
const FETCH_ATHLETE_PROFILE_BY_ID = 'FETCH_ATHLETE_PROFILE_BY_ID';

export {
  FETCH_TEAMS,
  FETCH_GAMES_BY_TEAM_ID,
  FETCH_GAME_STATISTIC_BY_ID,
  FILTER_GAMES_BY_STATUS_ID,
  FETCH_ATHLETE_PROFILE_BY_ID,
};
